# Generated by Django 3.0.3 on 2020-06-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='pers_prof',
            new_name='pers_desc',
        ),
    ]
