# Generated by Django 3.0.3 on 2020-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_auto_20200623_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
