# Generated by Django 3.0.3 on 2020-07-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_auto_20200706_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
